name: "Hello World"
description: "Greet someone"
inputs:
  github-token:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - run: npm ci
      shell: bash
    - name: Copy codegen.ts
      run: ./scripts/codegen.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Build
      run: npm run build
      shell: bash
