name: "Regenarate schema.graphql and Build"
inputs:
  github-token:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - run: npm ci
      shell: bash
    - name: Copy codegen.ts
      run: ./scripts/dl_schema.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    # schema.graphqlファイルの中にある@deprecatedがある行を削除する
    - name: Remove @deprecated
      run: sed -i '/@deprecated/d' schema.graphql
      shell: bash
      if: env.DEPRECATED_REMOVER
    - name: Generate code
      run: npx graphql-codegen
      shell: bash
    - name: Build
      run: npm run build
      shell: bash
