import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { useQuery } from "@apollo/client";
import { graphql } from "@/gql";
import { Post as PostType } from "@/gql/graphql"; // コンポーネントと名前がかぶるのでPostTypeにエイリアス
import { Post } from "@/components/Post";

const allPostsQueryDocument = graphql(/* GraphQL */ `
  query allPosts {
    posts {
      id
      ...PostFragment
    }
  }
`);

export default function Home() {
  const { data } = useQuery(allPostsQueryDocument);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="App">
          {data && (
            <ul>
              {data.posts.map((post: PostType, i: number) => (
                <li key={`${i}`}>
                  <Post name={post.name} comments={post.comments} />
                </li>
              ))}
            </ul>
          )}
        </div>
      </main>
    </>
  );
}
