name: CI
on: [pull_request]
env:
  REPO_NAME: konyu/graphql_rails

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: "src/**/*.{ts,tsx}"
          fail_on_error: true # 指摘が発生したらjobを失敗させる
  copy-and-regenerate:
    name: copy schema.graphql and regenarate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - name: Copy codegen.ts
        run: ./scripts/codegen.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: npm run build
      - name: Commit genarated code
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Codegen Change
  prettier:
    needs: [eslint, copy-and-regenerate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.{ts,tsx,js,jsx,json}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Run Prettier
        run: |
          npm ci
          npx prettier --write ${{ env.GIT_DIFF_FILTERED }}
        if: env.GIT_DIFF
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier Change
  jest:
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - name: Run test
        run: npm run test
