name: Codegen
on: [pull_request]
env:
  REPO_NAME: konyu/graphql_rails

jobs:
  copy-and-regenerate:
    name: copy schema.graphql and regenarate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - name: Copy codegen.ts
        run: ./scripts/codegen.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Codegen Change
